### ISSUE TITLE
Tab selecting for FF

### ISSUE THREAD

**Issue by YogurtTheHorse** [rmassidda/ulauncher-firefox-history#1]
This issue isn't connected to this extension directly, but you could create new extension for that or add to existing. Will be cool to select tabs from ulauncher

**Comment by rmassidda** [comment]
I think that the only way to get such information about tabs would be using an ad-hoc browser extension, like in this [equivalent extension for Chrome](https://github.com/brpaz/ulauncher-chrome-tabs).
If it wasn't so it would be a nice feature, I'll search for simpler solutions.

**Comment by YogurtTheHorse** [comment]
Not sure is that package works, but it looks like right what we are looking for: https://github.com/erikcw/firefox-tabs

Also there is an Selenium WebDriver API, may be it could help https://selenium-python.readthedocs.io/api.html

I didn't make any big research about these libs, but I may try do it a bit later

**Comment by rmassidda** [comment]
_firefox-tabs_ works great!
Selenium instead looks like a little too complex for the purpose, and it could be [tricky](https://selenium-python.readthedocs.io/installation.html#drivers) for the user to install.

By the way, once obtained the URLs the extension should open them inside the respective current tabs and not in a new tab like uLauncher API does.
