### ISSUE TITLE
"Not compatible with the latest version of Ulauncher"

### ISSUE THREAD

**Issue by NotAkitake** [rmassidda/ulauncher-firefox-history#2]
![Screenshot from 2019-07-03 12-21-57](https://user-images.githubusercontent.com/7873528/60584333-7cfd6e80-9d7c-11e9-8a02-b6e2ffff944e.png)

**Comment by rmassidda** [comment]
I haven't been using Ulauncher in a while.
For all I remember since v5 they rightly switched to Python3, this extension is written in Python2 so will only work in Ulauncher v4, that is still the stable release.

A rewrite shouldn't take much time.

**Comment by rmassidda** [comment]
Ok, it took really a short time.
Now it should work with Ulauncher v5, tested on Fedora30 with ulauncher_5.3.0.beta1.
