### ISSUE TITLE
Adjust to snap

### ISSUE THREAD

**Issue by shamiv** [rmassidda/ulauncher-firefox-history#5]
To make the extension work with the snap version of Firefox, I opened `history.py` and replaced `firefox_path = os.path.join(os.environ['HOME'], '.mozilla/firefox/')` with `firefox_path = os.path.join(os.environ['HOME'], 'snap/firefox/common/.mozilla/firefox/')`.

**Comment by janmechtel** [comment]
This helped me discover that FF has multiple profiles and the extension only uses Profile0, in my case I had to use Profile2
